### ISSUE TITLE
Paste URL of blank page is not intuitive

### ISSUE THREAD

**Issue by henfri** [breunigs/duplicity-amazondrive#14]
Hello,

I do not find posting the URL of the Blank Page intuitve after the authentication intuitive.
In duplicati 2.x, the whole Authentication is done via a web-browser. No Copy&Paste needed.
The problem here: The web-server that is run for the oauth session is accessible only on the local machine -which fails if it is headless.
Nevertheless, this might be an option to check.

In any case, I was totally unprepared for this blank page (also: I did not get a blank page, but a page with an error-message as 127.0.0.1 could not be reached (as I did not run this form the same machine duply is running on), despite the print out and thought something had failed. Maybe, this can be improved (no blank page?)

Greetings,
Hendrik

**Comment by breunigs** [comment]
I am aware of this issue, but none of the solutions are really appealing:
- run a local webserver that displays something. Requires more dependencies (prolly) and does not work headless
- redirect to domains under my control and display a "tutorial" there. Requires my infrastructure to never change
- Preferably such a page should live below http://duplicity.nongnu.org, but Amazon only allows redirect to `https`.
